### ISSUE TITLE
LaTeX con estilo Beamer

### ISSUE THREAD

**Issue by FelipeVargasv1** [FelipeVargasv1/Proyecto-I-D.Logico#20]
La primera diapositiva debe indicar los valores que se leyeron en la entrada de usuario (operandos, cantidad de bits, nombre del archivo de configuración).Las siguientes diapositivas deben demostrar el desarrollo completo de la multiplicación binaria y el
resultado final. En la última diapositiva se debe mostrar la información de la institución, integrantes, curso, año y semestre.

**Comment by Felipe-V13** [comment]
Actualizacion.
